config/routes.rb
Rails.application.routes.draw do
  resources :election_options
  resources :elections do
    member do
      get "apuracao"
    end
    collection do
      get "votar"
      get "recaptcha"
    end
  end
  resources :settings do
    collection do
      post "atualiza_settings"
      get "success"
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }

  resources :users

  root  "users#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id         :bigint           not null, primary key
#  namespace  :string
#  value      :json
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Setting < ApplicationRecord
  before_validation :format_value

  def to_s
    self.namespace
  end

  def self.get_value(namespace)
    s = Setting.find_by_namespace(namespace)
    if s.present?
      return s.value['value']
    end
    ''
  end

  def format_value
    if self.value.class == String
      self.value = JSON.parse(self.value)
    end
  end
  
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!, except: [:success]
  load_and_authorize_resource except: [:success]

  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  def index
    add_breadcrumb "Configurações", settings_path
    @q = Setting.all.ransack(params[:q])
    @settings = @q.result.page(params[:page])
  end

  def atualiza_settings
    params.reject{|a,b| ["action","commit","controller","redirect","logo"].include? a }.each do |p|

      s = Setting.find_or_initialize_by(namespace: p[0])
      s.value = {"value": p[1] == "1" ? true : p[1] == "0" ? false : p[1]}

      s.save
    end

    redirect_to params[:redirect], notice: "Atualizado com sucesso!"
  end

  # GET /settings/1
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  def create
    @setting = Setting.new(setting_params)

    if @setting.save
      redirect_to @setting, notice: 'Setting foi criado com sucesso'
    else
      render :new
    end
  end

  # PATCH/PUT /settings/1
  def update
    if @setting.update(setting_params)
      redirect_to @setting, notice: 'Setting foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /settings/1
  def destroy
    @setting.destroy
    redirect_to settings_url, notice: 'Setting foi apagado com sucesso.'
  end

  def success
    render layout: "devise"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def setting_params
      params.require(:setting).permit(:namespace, :value)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(setting) do |f| %>
  <% if setting.errors.any? %>
    <div id="error_explanation" class="card-panel red white-text">
      <h5><%= t('errors.template.header')  %>:</h5>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-panel">
  
  <div class="input-field">

    <%= f.label  :namespace %>
    <%= f.text_field :namespace %>
    
  </div>

  <div class="input-field">

    <%= f.label  :value %>
    <%= f.text_field :value %>
    
  </div>

</div>
  <div class="actions">
    <%= f.submit t('button.save'), class:"btn" %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.setting') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
					</li>
					<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.setting') %></a>
					</li>
					<li class="breadcrumb-item active"><%= t('breadcrumb.edit') %>
					</li>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), settings_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', setting: @setting %>

app/views/settings/index.html.erb
<div class="content-wrapper-before woffice-color"></div>
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span>Configurações</span></h5>
				<ol class="breadcrumbs mb-0">
					<%= render_breadcrumbs :tag => :li, :separator => "" %>
				</ol>
			</div>
		</div>
	</div>
</div>

<section class="invoice-list-wrapper section">
	<%= form_with url: atualiza_settings_settings_path, local: true do |f| %>
		<%= f.hidden_field  :redirect,  value: "/settings"%>
		<div class="card">
			<div class="card-content">
				<div class="row">
					<div class="col s12 l8">
						<div class="row">
							<div class="col s6">
								<p class="font-weight-600 left mr-5">Cadastro de Membros</p>
							</div>
							<div class="col s6">
								<div class="switch">
									<label>
										Desativado
										<%= f.check_box :cadastro_membros, checked: Setting.get_value("cadastro_membros") %>
										<span class="lever"></span>
										Ativado
									</label>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<%= f.submit "Salvar", class:"btn" %>
	<% end %>

</section>

app/views/settings/new.html.erb
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.setting') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
					</li>
					<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.setting') %></a>
					</li>
					<li class="breadcrumb-item active"><%= t('breadcrumb.new') %>
					</li>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), settings_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', setting: @setting %>

app/views/settings/show.html.erb
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
  <!-- Search for small screen-->
  <div class="container">
    <div class="row">
      <div class="col s10 m6 l6">
        <h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.setting') %></span></h5>
        <ol class="breadcrumbs mb-0">
          <li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
          </li>
          <li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.setting') %></a>
          </li>
          <li class="breadcrumb-item active"><%= t('breadcrumb.show') %>
          </li>
        </ol>
      </div>
      <div class="col s2 m6 l6">
        <%= link_to t('button.all'), settings_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
        <%= link_to edit_setting_path(@setting) , class: "btn-flat waves-effect waves-light breadcrumbs-btn right" do %>
          <i class="material-icons">edit</i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card-panel">
	
  <p>
    <strong><%= t('activerecord.attributes.setting.namespace') %>:</strong>
    <%= @setting.namespace %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.setting.value') %>:</strong>
    <%= @setting.value %>
  </p>

</div>

app/views/settings/success.html.erb
<div id class="row">
  <div class="input-field col s12 center">
    <img src="/images/FTV_2020_horizontal.png" alt="" class="responsive-img">
  </div>
</div>
Muito bem, agora nós vamos validar sua conta. <br>
 Você pode voltar em breve para verificar se sua conta já está ativa e utilizar seu email e senha que cadastrou agora.

<%= content_for :left_card do %>
  <div class="card-panel">
    Dúvidas e solicitações podem ser encaminhadas para: quadra@voleitocantins.com.br

  </div>
<% end %>