config/routes.rb
Rails.application.routes.draw do
  resources :election_options
  resources :elections do
    member do
      get "apuracao"
    end
    collection do
      get "votar"
      get "recaptcha"
    end
  end
  resources :settings do
    collection do
      post "atualiza_settings"
      get "success"
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }

  resources :users

  root  "users#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/election.rb
# == Schema Information
#
# Table name: elections
#
#  id         :bigint           not null, primary key
#  descricao  :text
#  fim        :datetime
#  inicio     :datetime
#  titulo     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Election < ApplicationRecord
  has_many :election_options

  accepts_nested_attributes_for :election_options, reject_if: :all_blank, allow_destroy: true

  #Método que verifica se a eleição está ativa
  def ativa?
    self.fim > DateTime.now
  end
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  before_action :set_election, only: [:apuracao,:show, :edit, :update, :destroy]

  # GET /elections
  def index
    add_breadcrumb "Eleições", elections_path
    if current_user.admin
      @q = Election.all.ransack(params[:q])
      @elections = @q.result.page(params[:page])
      render "index"
    else
      @elections = Election.where("? between inicio and fim", DateTime.now)
      render "public_elections"
    end

  end

  def public_elections
    @elections = Election.where("? between inicio and fim", DateTime.now)
  end

  def apuracao
    add_breadcrumb "Eleições", elections_path
    add_breadcrumb @election.titulo, election_path(@election)
    add_breadcrumb "Apuração", apuracao_election_path(@election)
    @votos = Vote.where(election_option_id: @election.election_options.pluck(:id))

  end

  def recaptcha
    render json: {}
  end

  def votar
    @eleicao = Election.find(params[:eleicao])
    if !@eleicao.ativa?
      redirect_to root_path, notice: "Eleição encerrada!"
      return
    end
    if current_user.member_votes.where(election_id: params[:eleicao]).last.present?

      redirect_to @eleicao, notice: "Você já votou!"
      return
    else
      Vote.create(election_option_id: params[:opcao], chave: SecureRandom.uuid)
      MemberVote.create(chave: SecureRandom.uuid, user_id: current_user.id, election_id: params[:eleicao])
      redirect_to @eleicao, notice: "Voto computado com sucesso!"
      return
    end

  end

  # GET /elections/1
  def show
    add_breadcrumb "Eleições", elections_path
    add_breadcrumb @election.titulo, election_path(@election)
    @voto = current_user.member_votes.where(election_id: @election.id).last
  end

  # GET /elections/new
  def new
    add_breadcrumb "Eleições", elections_path
    add_breadcrumb "Cadastrar", new_election_path
    @election = Election.new
  end

  # GET /elections/1/edit
  def edit
    add_breadcrumb "Eleições", elections_path
    add_breadcrumb "Alterar", edit_election_path(@election)
    if !current_user.admin
      redirect_to root_path
    end
  end

  # POST /elections
  def create
    @election = Election.new(election_params)

    if @election.save
      redirect_to @election, notice: 'Election foi criado com sucesso'
    else
      render :new
    end
  end

  # PATCH/PUT /elections/1
  def update
    if @election.update(election_params)
      redirect_to @election, notice: 'Election foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /elections/1
  def destroy
    @election.destroy
    redirect_to elections_url, notice: 'Election foi apagado com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_election
      @election = Election.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def election_params
      params.require(:election).permit(:titulo, :descricao, :inicio, :fim, election_options_attributes:[:id, :election_id, :descricao, :imagem, :nome, :numero, :_destroy])
    end
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/views/elections/_election_option_fields.html.erb
<div class="nested-fields">
  <div class="card">
    <div class="card-content">
      <div class="row">
        <div class="input-field">
          <%= f.label :nome %>
          <%= f.text_field :nome, required: true %>
        </div>
      </div>
      <div class="row">
        <div class="input-field">
          <%= f.label :descricao %>
          <%= f.text_area :descricao, {class:"materialize-textarea",required: true} %>
        </div>
      </div>
      <div class="row">
        <div class="input-field">
          <%= f.label :numero %>
          <%= f.text_field :numero, required: true %>
        </div>
      </div>

      <div class="row">
        <% if !f.object.new_record? %>
          <img src="<%= f.object.imagem.url %>" alt="">
          <% end %>
        <div class="file-field input-field white-text">
          <div class="btn">
            <span><i class="material-icons">attach_file</i></span>
            <%= f.file_field :imagem %>
            <%= f.hidden_field :imagem_cache %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate black-text" type="text" placeholder="Imagem 480x360">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/elections/_form.html.erb
<%= form_for(election) do |f| %>
  <% if election.errors.any? %>
    <div id="error_explanation" class="card-panel red white-text">
      <h5><%= t('errors.template.header')  %>:</h5>

      <ul>
      <% election.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-panel">
  
  <div class="input-field">

    <%= f.label  :titulo, "Título" %>
    <%= f.text_field :titulo, {required: true} %>
    
  </div>

  <div class="input-field">

    <%= f.label  :descricao, "Descrição" %>
    <%= f.text_area :descricao, class:"materialize-textarea" %>
    
  </div>

  <div class="input">

    <%= f.label  :inicio, "Início" %>
    <%= f.datetime_field :inicio, {required: true} %>
    
  </div>

  <div class="input">

    <%= f.label  :fim, "Término" %>
    <%= f.datetime_field :fim, {required: true} %>
    
  </div>

  <div class="card">
    <div class="card-content">
      <span class="card-title">Opções</span>
      <%= f.fields_for :election_options do |task| %>
        <%= render "election_option_fields", f: task %>

      <% end %>
      <div class="row">
        <%= link_to_add_association "Nova Opção", f, :election_options, class:"btn" %>
      </div>
    </div>
  </div>

</div>
  <div class="actions">
    <%= f.submit "Salvar", class:"btn" %>
  </div>
<% end %>

app/views/elections/apuracao.html.erb
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
  <!-- Search for small screen-->
  <div class="container">
    <div class="row">
      <div class="col s10 m6 l6">
        <h5 class="breadcrumbs-title mt-0 mb-0"><span>Eleição</span></h5>
        <ol class="breadcrumbs mb-0">
          <%= render_breadcrumbs :tag => :li, :separator => "" %>
        </ol>
      </div>
      <div class="col s2 m6 l6">
      </div>
    </div>
  </div>
</div>

<div class="card-panel">

  <div class="row">
    <div class="col s12 l4">
      <div class="card light-blue">
        <div class="card-content white-text">
            <span class="card-title">
              <%= @election.titulo %>
            </span>
          <p>
            <%= @election.descricao %>
          </p>
          <div class="row">
            <div class="col s6"><i class="material-icons">date_range</i><%= @election.inicio %></div>
            <div class="col s6"><i class="material-icons">date_range</i><%= @election.fim %></div>
          </div>
          <br>

        </div>
      </div>
    </div>
    <div class="col s12 l4">
      <div class="card light-green">
        <div class="card-content white-text">
          <span class="card-title">
            Total de Votos
          </span>
          <h2><%= @votos.size %></h2>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-content">
      <span class="card-title">Opções</span>
      <div class="row">
        <ul id="issues-collection" class="collection z-depth-1">
<!--          <li class="collection-item avatar">-->
<!--            <i class="material-icons red accent-2 circle">bug_report</i>-->
<!--            <h6 class="collection-header m-0">Issues</h6>-->
<!--            <p>Assigned to you</p>-->
<!--          </li>-->
        <% @election.election_options.each do |o| %>
          <li class="collection-item">
            <div class="row">
              <div class="col s7">
                <p class="collections-title">
                  <strong>#<%= o.numero %></strong> <%= o.nome %></p>
<!--                <p class="collections-content">Web Project</p>-->
              </div>
              <div class="col s2">
                <span class="task-cat deep-orange accent-2"><%= @votos.where(election_option_id: o.id).size %> Votos</span>
                <span class="task-cat green darken-4 "><%= (@votos.where(election_option_id: o.id).size * 100) / @votos.size %>%</span>
              </div>
              <div class="col s3">
                <div class="progress">
                  <div class="determinate" style="width: <%= (@votos.where(election_option_id: o.id).size * 100) / @votos.size %>%"></div>
                </div>
              </div>
            </div>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>

</div>








app/views/elections/edit.html.erb
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.election') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<%= render_breadcrumbs :tag => :li, :separator => "" %>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), elections_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', election: @election %>

app/views/elections/index.html.erb
<div class="content-wrapper-before woffice-color"></div>
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span>Eleições</span></h5>
				<ol class="breadcrumbs mb-0">
					<%= render_breadcrumbs :tag => :li, :separator => "" %>
				</ol>
			</div>
			<div class="col s2 m6 l6"><a class="btn white-text waves-effect waves-light breadcrumbs-btn right border-round" href="<%= new_election_path %>"><i class="material-icons hide-on-med-and-up">add</i><span class="hide-on-small-only">Cadastrar</span></a>
			</div>
		</div>
	</div>
</div>

<section class="invoice-list-wrapper section">
	<!-- create invoice button-->
	<!-- Options and filter dropdown button-->
	<div class="card">
		<div class="card-content">
			<div class="invoice-filter-action mr-3">
				<div class="row">
					<%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
						<div class="col s9 m11">
							<%= f.search_field :titulo_cont, placeholder: "Pesquisar", class: "search-ransack" %>
						</div>
						<div class="col s3 m1">
							<button type="submit" class="btn-floating mb-1 waves-effect waves-light rigth">
								<i class="material-icons">search</i>
							</button>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<p></p>
	<!-- create invoice button-->
	<div class="responsive-table">
		<style>td{padding: 15px}</style>
		<table class="table invoice-data-table white border-radius-4 pt-1">
			<thead>
			<tr>
				<th>Título</th>
				<th>Início</th>
				<th>Término</th>
				<th >Ações</th>
			</tr>
			</thead>
			<tbody>
			<% @elections.each do |election| %>
				<tr>
					<td><%= election.titulo %></td>
					<td><%= election.inicio %></td>
					<td><%= election.fim %></td>
					<td>
						<div class=" right-align">
							<%= link_to election, class: " mr-4" do %>
								<i class="material-icons">remove_red_eye</i>
							<% end %>
							<%= link_to edit_election_path(election) , class: " mr-4" do %>
								<i class="material-icons">edit</i>
							<% end %>
						</div>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
	<%= paginate(@elections)  %>
</section>

app/views/elections/new.html.erb
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.election') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<%= render_breadcrumbs :tag => :li, :separator => "" %>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), elections_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', election: @election %>

app/views/elections/public_elections.html.erb
<div class="row">
  <% @elections.each do |election| %>
    <div class="col s12 l4">
        <div class="card light-blue">
          <div class="card-content white-text">
            <span class="card-title">
              <%= election.titulo %>
            </span>
            <p>
              <%= election.descricao %>
            </p>
            <div class="row">
              <div class="col s6"><i class="material-icons">date_range</i><%= election.inicio %></div>
              <div class="col s6"><i class="material-icons">date_range</i><%= election.fim %></div>
            </div>
            <br>
            <div class="row">
              <%= link_to "Visualizar",election, class:"btn white blue-text" %>
            </div>
          </div>
        </div>
    </div>
  <% end %>
  <% if @elections.blank? %>
    <div class="card-panel center">
      <h4>Nenhuma votação está aberta neste momento.</h4>
    </div>
  <% end %>
</div>

app/views/elections/show.html.erb
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
  <!-- Search for small screen-->
  <div class="container">
    <div class="row">
      <div class="col s10 m6 l6">
        <h5 class="breadcrumbs-title mt-0 mb-0"><span>Eleição</span></h5>
        <ol class="breadcrumbs mb-0">
          <%= render_breadcrumbs :tag => :li, :separator => "" %>
        </ol>
      </div>
      <div class="col s2 m6 l6">
        <% if current_user.admin %>
          <%= link_to "Todas", elections_path, class:"btn white-text waves-effect waves-light breadcrumbs-btn right" %>
          <%= link_to edit_election_path(@election) , class: "btn-flat waves-effect waves-light breadcrumbs-btn right" do %>
            <i class="material-icons">edit</i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card-panel">
  <div class="row">
    <div class="col s12 l4">
      <div class="card light-blue">
        <div class="card-content white-text">
            <span class="card-title">
              <%= @election.titulo %>
            </span>
          <p>
            <%= @election.descricao %>
          </p>
          <div class="row">
            <div class="col s6"><i class="material-icons">date_range</i><%= @election.inicio %></div>
            <div class="col s6"><i class="material-icons">date_range</i><%= @election.fim %></div>
          </div>
          <br>

        </div>
      </div>
    </div>
    <div class="col s12 l4">
      <%= link_to  apuracao_election_path(@election) do  %>
        <div class="card green">
          <div class="card-content white-text center-align">
            <h2>Apuração</h2>
          </div>
        </div>
      <% end if current_user.admin %>
    </div>
  </div>
  <!--  <p>-->
  <!--    <strong>Título:</strong>-->
  <%#= @election.titulo %>
  <!--  </p>-->

  <!--  <p>-->
  <!--    <strong>Descrição:</strong>-->
  <%#= @election.descricao %>
  <!--  </p>-->

  <!--  <p>-->
  <!--    <strong>Início:</strong>-->
  <%#= @election.inicio %>
  <!--  </p>-->

  <!--  <p>-->
  <!--    <strong>Término:</strong>-->
  <%#= @election.fim %>
  <!--  </p>-->



  <div class="card">
    <div class="card-content">
      <span class="card-title">Opções</span>
      <div class="row">
        <% @election.election_options.each do |o| %>

          <div class="col s12 m4">
            <div class="card">
              <div class="card-image">
                <img src="<%= o.imagem.present? ? o.imagem.url : '/materialize/images/gallary/13.png' %>">
                <!--                <a class="btn-floating halfway-fab waves-effect waves-light blue left">-->
                <!--                  <i class="material-icons">share</i>-->
                <!--                </a>-->
              </div>
              <div class="card-content">
                <h5 class="center font-weight-400"><%= o.nome %></h5>
                <p class="center"># <%= o.numero %></p>
                <div class="divider mt-5"></div>
                <br>
                <div class="col s12 center">
                  <% if !@voto.present? and current_user.pode_votar? %>
                    <a href="#modal" onclick="set_id(<%= o.id %>)" class="btn white- modal-trigger">Votar</a>
                  <% end %>
                </div>
                <br>
                <!--                <div class="col l6 m6 s6 padding-5">-->
                <!--                  <p class="center">-->
                <!--                    <i class="material-icons">person_add</i>-->
                <!--                  </p>-->
                <!--                  <p class="center">Votos</p>-->
                <!--                  <p class="center">124k</p>-->
                <!--                </div>-->
                <!--                <div class="col l6 m6 s6 padding-5">-->
                <!--                  <p class="center">-->
                <!--                    <i class="material-icons">person</i>-->
                <!--                  </p>-->
                <!--                  <p class="center">following</p>-->
                <!--                  <p class="center">432</p>-->
                <!--                </div>-->
              </div>
            </div>
          </div>



        <% end %>
      </div>
    </div>
  </div>

</div>

<div id="modal" class="modal">

  <div class="modal-content">
    <h4>Confirme seu Voto!</h4>
    <%= form_with url: recaptcha_elections_path, method: :get do |f| %>
      <p>É necessário confirmar seu voto enviando um SMS para <%= current_user.telefone %></p>
      <!--                <a href="#" id="sign-in-button"  class="btn white-text"> <i class="material-icons">textsms</i>Enviar Código</a>-->

      <button type="submit" id="sign-in-button" class="btn white-text"> <i class="material-icons">textsms</i>Enviar Código</a> </button>
    <% end %>
    <br>
    <%= form_with url: votar_elections_path,id: "form_code", method: :get, local: true do |f| %>
      <%= f.hidden_field :opcao, id:"opcao" %>
      <%= f.hidden_field :eleicao, value: @election.id %>
      <input type="text" name="codigo" id="codigo" placeholder="Informe o Código">
      <a href="#" onclick="check_code();" class="waves-effect waves-green btn white-text">Votar</a>
      </div>
      <div class="modal-footer">

        <!--        <button  class="modal-close waves-effect waves-green btn-flat">Votar </button>-->
        <!--              <a href="#" id="sign-in-button" class="modal-close waves-effect waves-green btn-flat">Agree</a>-->
      </div>
    <% end %>
    </div>



<% content_for :scripts do %>
  <script type="text/javascript" charset="utf-8">
      function set_id(id)
      {
          $("#opcao").val(id);
      }

      var firebaseConfig = {
          apiKey: "AIzaSyCN0ioMiusG0uo4RvI6mMtO7uATEYhl3n0",
          authDomain: "federacao-volei.firebaseapp.com",
          databaseURL: "https://federacao-volei.firebaseio.com",
          projectId: "federacao-volei",
          storageBucket: "federacao-volei.appspot.com",
          messagingSenderId: "516472202204",
          appId: "1:516472202204:web:f2e26ee8398c864bae6519"
      };
      // Initialize Firebase
      firebase.initializeApp(firebaseConfig);
      firebase.auth().languageCode = 'it';

      window.recaptchaVerifier = new firebase.auth.RecaptchaVerifier('sign-in-button', {
          'size': 'invisible',
          'callback': function(response) {
              // reCAPTCHA solved, allow signInWithPhoneNumber.
              console.log("solved");
              send_sms();
          }
      });

      recaptchaVerifier.render().then(function(widgetId) {
          window.recaptchaWidgetId = widgetId;
      });



      function send_sms()
      {
          var appVerifier = window.recaptchaVerifier;
          firebase.auth().signInWithPhoneNumber("+55<%= current_user.telefone %>", appVerifier)
              .then(function (confirmationResult) {
                  // SMS sent. Prompt user to type the code from the message, then sign the
                  // user in with confirmationResult.confirm(code).
                  window.confirmationResult = confirmationResult;
                  console.log("SMS ENVIADO");
                  Swal.fire("","Código enviado","success");

              }).catch(function (error) {
              console.log("ERRROR SMS");
          });
      }

      function check_code()
      {
          var code = $("#codigo").val();
          if(code == "")
          {
              Swal.fire("","Informe o Código","error");
              return;
          }
          window.confirmationResult.confirm(code).then(function (result) {
              // User signed in successfully.
              var user = result.user;
              console.log("checado");
              $("#form_code").submit();
          }).catch(function (error) {
              // User couldn't sign in (bad verification code?)
              // ...
              Swal.fire("","Código inválido","error");
          });
      }
  </script>
<% end %>