config/routes.rb
Rails.application.routes.draw do
  resources :election_options
  resources :elections do
    member do
      get "apuracao"
    end
    collection do
      get "votar"
      get "recaptcha"
    end
  end
  resources :settings do
    collection do
      post "atualiza_settings"
      get "success"
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }

  resources :users

  root  "users#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/election_option.rb
# == Schema Information
#
# Table name: election_options
#
#  id          :bigint           not null, primary key
#  descricao   :text
#  imagem      :string
#  nome        :string
#  numero      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  election_id :bigint           not null
#
# Indexes
#
#  index_election_options_on_election_id  (election_id)
#
# Foreign Keys
#
#  fk_rails_...  (election_id => elections.id)
#
class ElectionOption < ApplicationRecord
  belongs_to :election
  mount_uploader :imagem, DocumentoUploader
end

app/controllers/election_options_controller.rb
class ElectionOptionsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_election_option, only: [:show, :edit, :update, :destroy]

  # GET /election_options
  def index
    @q = ElectionOption.all.ransack(params[:q])
    @election_options = @q.result.page(params[:page])
  end

  # GET /election_options/1
  def show
  end

  # GET /election_options/new
  def new
    @election_option = ElectionOption.new
  end

  # GET /election_options/1/edit
  def edit
  end

  # POST /election_options
  def create
    @election_option = ElectionOption.new(election_option_params)

    if @election_option.save
      redirect_to @election_option, notice: 'Election option foi criado com sucesso'
    else
      render :new
    end
  end

  # PATCH/PUT /election_options/1
  def update
    if @election_option.update(election_option_params)
      redirect_to @election_option, notice: 'Election option foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /election_options/1
  def destroy
    @election_option.destroy
    redirect_to election_options_url, notice: 'Election option foi apagado com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_election_option
      @election_option = ElectionOption.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def election_option_params
      params.require(:election_option).permit(:election_id, :nome, :descricao, :numero, :imagem)
    end
end

app/helpers/election_options_helper.rb
module ElectionOptionsHelper
end

app/views/election_options/_form.html.erb
<%= form_for(election_option) do |f| %>
  <% if election_option.errors.any? %>
    <div id="error_explanation" class="card-panel red white-text">
      <h5><%= t('errors.template.header')  %>:</h5>

      <ul>
      <% election_option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-panel">
  
  <div class="input-field">
    <%= f.collection_select :election_id, Election.all, :id, :name, prompt: true  %>
    
  </div>

  <div class="input-field">

    <%= f.label  :nome %>
    <%= f.text_field :nome %>
    
  </div>

  <div class="input-field">

    <%= f.label  :descricao %>
    <%= f.text_area :descricao %>
    
  </div>

  <div class="input-field">

    <%= f.label  :numero %>
    <%= f.text_field :numero %>
    
  </div>

  <div class="input-field">

    <%= f.label  :imagem %>
    <%= f.text_field :imagem %>
    
  </div>

</div>
  <div class="actions">
    <%= f.submit t('button.save'), class:"btn" %>
  </div>
<% end %>

app/views/election_options/edit.html.erb
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.election_option') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
					</li>
					<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.election_option') %></a>
					</li>
					<li class="breadcrumb-item active"><%= t('breadcrumb.edit') %>
					</li>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), election_options_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', election_option: @election_option %>

app/views/election_options/index.html.erb
<div class="content-wrapper-before woffice-color"></div>
			<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
				<!-- Search for small screen-->
				<div class="container">
					<div class="row">
						<div class="col s10 m6 l6">
							<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.election_options') %></span></h5>
							<ol class="breadcrumbs mb-0">
								<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
								</li>
								<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.election_options') %></a>
								</li>
								<li class="breadcrumb-item active"><%= t('breadcrumb.list') %>
								</li>
							</ol>
						</div>
						<div class="col s2 m6 l6"><a class="btn waves-effect waves-light breadcrumbs-btn right border-round" href="<%= new_election_option_path %>"><i class="material-icons hide-on-med-and-up">add</i><span class="hide-on-small-only"><%= t("button.add")  %> <%= t('activerecord.models.election_option') %></span></a>
						</div>
					</div>
				</div>
			</div>

<section class="invoice-list-wrapper section">
  <!-- create invoice button-->
  <!-- Options and filter dropdown button-->
  <div class="invoice-filter-action mr-3">
    <div class="row">
    <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
      <div class="col s9 m11">
          <%= f.search_field :election_cont, placeholder: t('placeholder.search'), class: "search-ransack" %>     
      </div>
      <div class="col s3 m1">
				<button type="submit" class="btn-floating mb-1 waves-effect waves-light rigth">
					<i class="material-icons">search</i>
				</button>
      </div>
    <% end %>
    </div>
  </div>
  <p></p>
  <!-- create invoice button-->
  <div class="responsive-table">
    <style>td{padding: 15px}</style>
    <table class="table invoice-data-table white border-radius-4 pt-1">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.election_option.election') %></th>
          <th><%= t('activerecord.attributes.election_option.nome') %></th>
          <th><%= t('activerecord.attributes.election_option.descricao') %></th>
          <th><%= t('activerecord.attributes.election_option.numero') %></th>
          <th><%= t('activerecord.attributes.election_option.imagem') %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @election_options.each do |election_option| %>
        <tr>
            <td><%= election_option.election %></td>
            <td><%= election_option.nome %></td>
            <td><%= election_option.descricao %></td>
            <td><%= election_option.numero %></td>
            <td><%= election_option.imagem %></td>
          <td>
            <div class="invoice-action right-align">
              <%= link_to election_option, class: "invoice-action-view mr-4" do %>
                <i class="material-icons">remove_red_eye</i>
              <% end %>
              <%= link_to edit_election_option_path(election_option) , class: "invoice-action-edit mr-4" do %>
                <i class="material-icons">edit</i>
              <% end %>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate(@election_options)  %>
</section>

app/views/election_options/new.html.erb
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.election_option') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
					</li>
					<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.election_option') %></a>
					</li>
					<li class="breadcrumb-item active"><%= t('breadcrumb.new') %>
					</li>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), election_options_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', election_option: @election_option %>

app/views/election_options/show.html.erb
<div class="breadcrumbs-light pb-0 pt-4" id="breadcrumbs-wrapper">
  <!-- Search for small screen-->
  <div class="container">
    <div class="row">
      <div class="col s10 m6 l6">
        <h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.election_option') %></span></h5>
        <ol class="breadcrumbs mb-0">
          <li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
          </li>
          <li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.election_option') %></a>
          </li>
          <li class="breadcrumb-item active"><%= t('breadcrumb.show') %>
          </li>
        </ol>
      </div>
      <div class="col s2 m6 l6">
        <%= link_to t('button.all'), election_options_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
        <%= link_to edit_election_option_path(@election_option) , class: "btn-flat waves-effect waves-light breadcrumbs-btn right" do %>
          <i class="material-icons">edit</i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card-panel">
	
  <p>
    <strong><%= t('activerecord.attributes.election_option.election') %>:</strong>
    <%= @election_option.election %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.election_option.nome') %>:</strong>
    <%= @election_option.nome %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.election_option.descricao') %>:</strong>
    <%= @election_option.descricao %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.election_option.numero') %>:</strong>
    <%= @election_option.numero %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.election_option.imagem') %>:</strong>
    <%= @election_option.imagem %>
  </p>

</div>